version: "2"
linters:
  enable:
    - misspell
    - unconvert
  disable:
    - errcheck
  settings:
    govet:
      disable:
        - inline
    staticcheck:
      checks:
        - "SA*"
    revive:
      rules:
        # TODO(thaJeztah): temporarily disabled the "unused-parameter" check.
        # It produces many warnings, and some of those may need to be looked at.
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1019: .*io/ioutil.*'
      - linters:
          - govet
        text: 'printf: non-constant format string in call to \(\*testing\.common\)\.(Fatalf|Errorf)'
      - linters:
          - staticcheck
        text: 'SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead'
      - linters:
          - staticcheck
        text: 'SA1019: .*(github\.com/aws/aws-sdk-go).*'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
